server:
  port: 8079

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/ai_bill_test?useCursorFetch=true&autoReconnect=true&useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root