server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 127.0.0.1
    prot: 5672
    username: dev
    password: dev
    virtual-host: /dev
    listener:
      simple:
        # 设置消费消息手动签收，如果设置成none，则消息从队列中出来，则认为已经消费了
        acknowledge-mode: manual
        # 设置消费线程的并发数也就是通道数量（默认一个通道最大未确认消息数为250，就是prefetch为250，官方建议设置在200~300之间）
        concurrency: 1
        # 设置消费线程的最大并发数
        max-concurrency: 1
        # 一个通道最多能消费的unacked messages数目
        prefetch: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 10