server:
  port: 8100


dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    parameters:
      namespace: dubboDemo
    # 测试dubbo调用策略
#  application:
#    owner: hupeng

spring:
  application:
    name: dubbo-springboot-provider
