server:
  port: 7000

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    parameters:
      namespace: dubboDemo
  # 指定dubbo调用策略
  consumer:
    loadbalance: sameOwnerPriority
  application:
    owner: hupeng

spring:
  application:
    name: dubbo-springboot-consumer
